// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TodoListApi.Models.DB;

#nullable disable

namespace TodoListApi.Migrations
{
    [DbContext(typeof(TodoTaskDB))]
    partial class TodoTaskDBModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TodoListApi.Models.Data.TodoTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("TodoTasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "This is some dummy text",
                            Title = "This is my task!",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "This is some dummy text",
                            Title = "This is my task!",
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            Description = "This is some dummy text",
                            Title = "This is my task!",
                            UserId = 3
                        });
                });

            modelBuilder.Entity("TodoListApi.Models.Data.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "test1@gmail.com",
                            Password = "8NAamnmoYvbfsi8FkwuCgQ==",
                            Role = "user",
                            UserName = "test1"
                        },
                        new
                        {
                            Id = 2,
                            Email = "test2@gmail.com",
                            Password = "8NAamnmoYvbfsi8FkwuCgQ==",
                            Role = "user",
                            UserName = "test2"
                        },
                        new
                        {
                            Id = 3,
                            Email = "test3@gmail.com",
                            Password = "8NAamnmoYvbfsi8FkwuCgQ==",
                            Role = "admin",
                            UserName = "test3"
                        });
                });

            modelBuilder.Entity("TodoListApi.Models.Data.TodoTask", b =>
                {
                    b.HasOne("TodoListApi.Models.Data.User", "User")
                        .WithMany("Tasks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("TodoListApi.Models.Data.User", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
